import numpy as np
import matplotlib.pyplot as plt

x2_1 = np.genfromtxt("build/teil1.txt", unpack=True, usecols=0)
y2_1 = np.genfromtxt("build/teil1.txt", unpack=True, usecols=1)
x2_2 = np.genfromtxt("build/teil2.txt", unpack=True, usecols=0)
y2_2 = np.genfromtxt("build/teil2.txt", unpack=True, usecols=1)
x2_3 = np.genfromtxt("build/teil3.txt", unpack=True, usecols=0)
y2_3 = np.genfromtxt("build/teil3.txt", unpack=True, usecols=1)
z2_3 = np.genfromtxt("build/teil3.txt", unpack=True, usecols=2)

plt.subplot(2, 2, 1)
plt.plot(x2_1, y2_1, '-k', label="Teil 1")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend(loc="best")
plt.subplot(2, 2, 2)
plt.plot(x2_2, y2_2, '-k', label="Teil2")
plt.xlabel("x")
plt.ylabel("f(x)")
plt.legend(loc="best")
#plt.subplot(2, 2, 3)
#plt.plot()
plt.tight_layout()
plt.savefig("contents/aufgabe2_1.pdf")
plt.close()
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.plot(x2_3, y2_3, z2_3, label="Teil3")
ax.set_xlabel("x")
ax.set_ylabel("d")
ax.set_zlabel("f(x)")
ax.legend(loc="best")
plt.savefig("contents/aufgabe2_1a.pdf")
plt.close()